### PR TITLE
[#153] Look for exact match first

### LINKED ISSUE #153: [BUG] Wrong user is picked when several usernames with same substring found
**Describe the bug**
When creating a personal WIP-limit you cannot point to specific user when several matches are available. 

**To Reproduce**
- For example, we have two Jira users with following usernames:
    - `a.d.naumova`
    - `d.naumov`
- Go to board settings -> Columns -> Manage per-person WIP-limits
- Type `d.naumov` in "Person JIRA name" field
- Click "Add limit"
- WIP-limit is created for `a.d.naumova` and there is no other ways to override this behaviour

**Expected behavior**
Exact username match should happen

**Screenshots**
image

### PR DESCRIPTION
**Pull request by nezed**
Fixes #153

### CODE REVIEW

File: src/shared/jiraApi.js [hunk 1]
```diff
@@ -168,5 +168,13 @@ export const getUser = query =>
       if (res2.status === 'fulfilled') return res2.value;
     })
     .then(users => {
-      return users.find(user => user.name?.includes(query) || user.displayName?.includes(query)) ?? users[0];
+      if (!query) return users[0];
+
+      const exactMatch = users.find(user => user.name === query || user.displayName === query);
```
Comment (nezed) [inline src/shared/jiraApi.js:173]: Jira lookups only by substring, so Levenshtein distance probably would be an overkill

**Review by davakh — APPROVED** [review]
